#!/bin/bash
# Task cleanup script generated by Task Master

cd /home/midori-ai/workspace

echo "=== Task Master: Cleaning up task files ==="
echo ""

echo "1. Deleting completed tasks from taskmaster/..."
rm -v .agents/tasks/taskmaster/T001-investigate-duplicate-logs.md
rm -v .agents/tasks/taskmaster/T007-reproduce-and-analyze-duplicate-logs.md
rm -v .agents/tasks/taskmaster/T008-implement-fix-for-duplicate-logs.md

echo ""
echo "2. Moving T009 to wip/ (needs user testing)..."
mv -v .agents/tasks/taskmaster/T009-verify-fix-and-cleanup-debug-code.md .agents/tasks/wip/

echo ""
echo "3. Deleting obsolete tasks from wip/..."
rm -v .agents/tasks/wip/T001-investigate-log-deduplication-strategy.md
rm -v .agents/tasks/wip/T002-add-log-deduplication-to-on-task-log.md
rm -v .agents/tasks/wip/T004-coordinate-bridge-and-recovery-log-readers.md
rm -v .agents/tasks/wip/T006-add-debug-logging-to-log-sources.md

echo ""
echo "=== Remaining tasks in taskmaster/ ==="
ls -1 .agents/tasks/taskmaster/

echo ""
echo "=== Remaining tasks in wip/ ==="
ls -1 .agents/tasks/wip/

echo ""
echo "✓ Task cleanup complete!"
