"""TYPE_CHECKING-only contracts for mixin classes.

These base classes tell basedpyright what attributes, methods, and signals
each mixin can expect from its runtime host (MainWindow or EnvironmentsPage).
They exist purely for static analysis and add zero runtime overhead.
"""

from __future__ import annotations

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    import threading
    from PySide6.QtCore import QThread, QTimer, Signal
    from PySide6.QtWidgets import (
        QComboBox,
        QCheckBox,
        QLineEdit,
        QStackedWidget,
        QToolButton,
    )
    from agents_runner.core.agent.watch_state import AgentWatchState
    from agents_runner.environments import Environment
    from agents_runner.ui.bridges import TaskRunnerBridge
    from agents_runner.ui.graphics import GlassRoot
    from agents_runner.ui.pages import (
        DashboardPage,
        EnvironmentsPage,
        NewTaskPage,
        SettingsPage,
        TaskDetailsPage,
        TasksPage,
    )
    from agents_runner.ui.radio import RadioController
    from agents_runner.ui.task_event_proxy import TaskEventProxy
    from agents_runner.ui.task_model import Task


class _MainWindowHints:
    if TYPE_CHECKING:
        _settings_data: dict[str, object]
        _environments: dict[str, Environment]
        _syncing_environment: bool
        _tasks: dict[str, Task]
        _threads: dict[str, QThread]
        _bridges: dict[str, TaskRunnerBridge]
        _task_event_proxies: dict[str, TaskEventProxy]
        _interactive_prep_threads: dict[str, QThread]
        _interactive_prep_workers: dict[str, object]
        _interactive_prep_bridges: dict[str, object]
        _interactive_prep_context: dict[str, dict[str, object]]
        _run_started_s: dict[str, float]
        _dashboard_log_refresh_s: dict[str, float]
        _interactive_watch: dict[str, tuple[str, threading.Event]]
        _repo_branches_request_id: int
        _repo_branches_request_meta: dict[int, dict[str, object]]
        _repo_branches_cache: dict[str, list[str]]
        _task_workspace_cleanup_last_check_s: float
        _task_workspace_cleanup_running: bool
        _task_workspace_migration_thread: QThread | None
        _task_workspace_migration_worker: object | None
        _state_path: str
        _save_timer: QTimer
        _task_event_drain_timer: QTimer
        _watch_states: dict[str, AgentWatchState]
        _dashboard_ticker: QTimer
        _recovery_log_stop: dict[str, threading.Event]
        _finalization_threads: dict[str, threading.Thread]
        _radio_channel_options: list[str]
        _recovery_ticker: QTimer
        _radio_controller: RadioController
        _root: GlassRoot
        _btn_home: QToolButton
        _btn_new: QToolButton
        _btn_envs: QToolButton
        _btn_settings: QToolButton
        _details: TaskDetailsPage
        _dashboard: DashboardPage
        _new_task: NewTaskPage
        _envs_page: EnvironmentsPage
        _settings: SettingsPage
        _tasks_page: TasksPage
        _stack: QStackedWidget
        _agent_selection_round_robin_cursor: int
        _fork_notice_seen: set[str]
        _current_env_name: str

        host_log: Signal
        host_pr_url: Signal
        host_artifacts: Signal
        interactive_finished: Signal
        repo_branches_ready: Signal

        def _schedule_save(self, *_args: object) -> None: ...
        def _save_state(self, *_args: object) -> None: ...
        def _should_archive_task(self, task: Task) -> bool: ...
        def _on_task_log(self, task_id: str, log_line: str) -> None: ...
        def _on_bridge_state(self, *args: object) -> None: ...
        def _on_bridge_log(self, *args: object) -> None: ...
        def _on_bridge_done(self, *args: object) -> None: ...
        def _on_bridge_retry_attempt(self, *args: object) -> None: ...
        def _on_bridge_agent_switched(self, *args: object) -> None: ...
        def _try_sync_container_state(self, task_id: str) -> None: ...
        def _queue_task_finalization(self, task_id: str) -> None: ...
        def _show_dashboard(self) -> None: ...
        def _show_tasks(self) -> None: ...
        def _show_task_details(self) -> None: ...
        def _show_environments(self) -> None: ...
        def _show_settings(self) -> None: ...
        def _show_new_task(self) -> None: ...
        def _maybe_auto_navigate_on_task_start(self, task_id: str) -> None: ...
        def _active_environment_id(self) -> str: ...
        def _coerce_agent_override(
            self, agent_override: object
        ) -> dict[str, str] | None: ...
        def _resolve_override_config_dir(self, *args: object) -> str | None: ...
        def _select_agent_instance_for_env(self, *args: object) -> object: ...
        def _effective_agent_and_config(self, *args: object) -> object: ...
        def _resolve_config_dir_for_agent(self, *args: object) -> str: ...
        def _new_task_workspace(self, *args: object) -> str: ...
        def _ensure_agent_config_dir(self, *args: object) -> str: ...
        def _commit_round_robin_selection(self, *args: object) -> None: ...
        def _effective_gpu_enabled(self, *args: object) -> bool: ...
        def _default_interactive_command(self, *args: object) -> str: ...
        def _effective_opencode_interactive_mode(self, *args: object) -> str: ...
        def _is_agent_help_interactive_launch(self, *args: object) -> bool: ...
        def _effective_host_config_dir(self, *args: object) -> str: ...
        def _get_next_agent_info(self, *args: object) -> dict[str, object] | None: ...
        def _remember_environment_base_branch(self, *args: object) -> str | None: ...
        def _refresh_task_rows(self) -> None: ...
        def _refresh_active_environment_repo_branches(self) -> None: ...
        def _populate_environment_pickers(self, *args: object) -> None: ...
        def _update_window_title_from_radio_state(self) -> None: ...
        def _apply_active_environment_to_new_task(self) -> None: ...
        def _can_start_new_agent_for_env(self, *args: object) -> bool: ...
        def _actually_start_task(self, task: Task) -> None: ...
        def _start_task_from_ui(self, *args: object) -> str | None: ...
        def _reconcile_tasks_after_restart(self) -> None: ...
        def _try_start_queued_tasks(self) -> None: ...
        def _update_task_ui(self, task_id: str) -> None: ...
        def _force_remove_container(self, container_id: str) -> None: ...
        def _finalize_gh_management_worker(self, *args: object) -> None: ...
        def _start_artifact_finalization(self, *args: object) -> None: ...
        def _compute_cross_agent_config_mounts(
            self, *args: object
        ) -> list[tuple[str, str]]: ...
        def _sync_radio_controller_from_settings(self) -> None: ...
        def _refresh_new_task_agent_info(self) -> None: ...
        def _environment_list(self) -> list[Environment]: ...
        def _environment_effective_workdir(self, *args: object) -> str: ...
        def _user_environment_map(self) -> dict[str, str]: ...
        def _is_internal_environment_id(self, *args: object) -> bool: ...
        def _refresh_radio_channel_options(self) -> None: ...


class _EnvironmentsPageHints:
    if TYPE_CHECKING:
        _environments: dict[str, Environment]
        _current_env_id: str | None
        _settings_data: dict[str, object]
        _suppress_autosave: bool
        _autosave_timer: QTimer
        _advanced_autosave_timer: QTimer

        _workspace_type_combo: QComboBox
        _workspace_target: QLineEdit
        _gh_use_host_cli: QCheckBox
        _gh_management_browse: QToolButton
        _name: QLineEdit
        _max_agents_running: QLineEdit
        _color: QComboBox
        _env_select: QComboBox
        _headless_desktop_enabled: QCheckBox
        _cache_desktop_build: QCheckBox
        _container_caching_enabled: QCheckBox
        _use_cross_agents: QCheckBox
        _gh_context_enabled: QCheckBox
        _github_polling_enabled: QCheckBox
        _agentsnova_trusted_mode: QComboBox
        _agentsnova_auto_review_mode: QComboBox
        _agentsnova_auto_reactions_mode: QComboBox
        _agentsnova_marker_comment_mode: QComboBox
        _interactive_pr_no_prompt_mode: QComboBox
        _interactive_pr_prompt_enabled: QCheckBox
        _setup_agents_missing_prompt_enabled: QCheckBox
        _interactive_pull_before_run_enabled: QCheckBox
        _gh_branch_work_mode: QComboBox
        _gh_task_branch_naming_style: QComboBox
        _gh_task_branch_custom_template: QLineEdit
        _gpu_override_mode: QComboBox
        _opencode_interactive_mode: QComboBox
        _cache_system_preflight_enabled: QCheckBox
        _cache_settings_preflight_enabled: QCheckBox
        _env_vars_tab: object
        _mounts_tab: object
        _ports_tab: object
        _prompts_tab: object
        _agents_tab: object
        _agentsnova_trusted_users_env: object

        _pane_specs: list[object]
        _active_pane_key: str
        _nav_buttons: dict[str, QToolButton]
        _pane_index_by_key: dict[str, int]
        _page_stack: QStackedWidget
        _compact_nav: QComboBox
        _nav_scroll: object
        _compact_mode: bool
        _pane_animation: object | None
        _pane_rest_pos: object | None

        updated: Signal
        test_preflight_requested: Signal
        back_requested: Signal

        def _sync_workspace_controls(self, *args: object) -> None: ...
        def _issue_294_environment_values(self) -> dict[str, object]: ...
        def _draft_environment_from_form(self, *args: object) -> Environment | None: ...
        def try_autosave(self, *args: object, **kwargs: object) -> bool: ...
        def _queue_debounced_autosave(self, *args: object) -> None: ...
        def _queue_advanced_autosave(self, *args: object) -> None: ...
        def _emit_autosave(self) -> None: ...
        def _default_pane_specs(self) -> list[object]: ...
        def _apply_environment_tints(self) -> None: ...
        def _on_headless_desktop_toggled(self, *args: object) -> None: ...
        def _on_container_caching_toggled(self, *args: object) -> None: ...
        def _on_use_cross_agents_toggled(self, *args: object) -> None: ...
        def _sync_interactive_pr_controls(self) -> None: ...
        def _sync_github_branch_naming_controls(self) -> None: ...
        def _on_ports_changed(self) -> None: ...
        def _on_prompts_changed(self) -> None: ...
        def _on_agents_changed(self) -> None: ...
        def _on_setup_environment_github_defaults(self) -> None: ...
        def _navigate_to_pane(self, key: str) -> None: ...
        def _set_active_navigation(self, key: str) -> None: ...
        def _set_current_pane(self, key: str) -> None: ...
        def _animate_stack(self, *args: object) -> None: ...
        def _build_navigation(self) -> None: ...
        def _current_environment(self) -> Environment | None: ...
